import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // html'ye h-full verdik
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      {/* body'ye h-full ve flex-col ekledik */}
      <body className="h-full flex flex-col">
        <div className="navbar bg-base-100 shadow-sm">
          <a className="btn btn-ghost text-xl">daisyUI</a>
        </div>

        {/* main'e flex-1 vererek tüm boşluğu kaplamasını sağladık. 
            Buraya bg-base-200 gibi bir renk eklersen tüm boşluğun o renk olduğunu göreceksin. */}
        <main className="flex-1 bg-base-0">{children}</main>
      </body>
    </html>
  );
}
